# 服务提供方
spring:
  application:
    name: dubbo-service-provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: zhuima522..
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: dubbo-provider
  registry:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
#    设置实现类所在包
    base-packages: com.example.dubbo.provider.service.impl
# 设置超时时间
  provider:
    timeout: 5000

# 自定义zookeeper配置
zookeeper:
  #每次重试时间间隔，单位毫秒
  baseSleepTimeMs: 1000
  #重试次数
  maxRetries: 3
  #zookeeper服务连接id与端口
  connectString: 127.0.0.1:2181
  #会话超时时间，单位毫秒
  sessionTimeoutMs: 5000
  #连接创建超时时间，单位毫秒
  connection-timeout-ms: 5000



#seata 配置
server:
  port: 7000
seata:
  enabled: true
  application-id: stock-seata-example
  tx-service-group: my_test_tx_group
  service:
    grouplist:
      default: 127.0.0.1:8091
