server:
  port: 1003

spring:
  application:
    name: alibaba-cloud-sentinel

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:9090
        port: 8719


management:
  endpoints:
    web:
      exposure:
        include: "*"