# 服务消费方
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: zhuima522..
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: dubbo-service-consumer


dubbo:
  application:
    name: dubbo-consumer
  registry:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout: 2000

server:
  port: 8000



#seata 配置
seata:
  enabled: true
  application-id: stock-seata-example
  tx-service-group: my_test_tx_group
  service:
    grouplist:
      default: 127.0.0.1:8091